### ISSUE TITLE
Run with openvpn existing server?

### ISSUE THREAD

**Issue by renanwilliam** [adamwalach/openvpn-web-ui#3]
How configure this to use a openvpn existing server?

**Comment by ocervell** [comment]
+1 Haven't been able to set up the UI for existing server following DigitalOcean tutorial

**Comment by adamwalach** [comment]
Hi,
Sorry for late response. In the next few weeks I'll try to refresh this project a bit and hopefully I'll create a step-by-step tutorial how to use it with existing server. Stay tuned!

**Comment by Gasman2014** [comment]
It would be good to be able to use this with an existing installation. I managed to get Docker onto my Stretch OpenVPN Pi box and install your docker image but it fell over as the VPN port was already in use. It would be worth making this point in the ReadMe.md as it is not clear that it needs a different config for an existing installation.

I would be very pleased see this developed though as it is the best looking interface to OpenVPN by far.

**Comment by jonathan-d-palumbo** [comment]
Was there ever any documentation added on how to use this with and existing OpenVPN server installation?
